import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";
import type { Locale } from "@/lib/i18n";

export const metadata: Metadata = {
  title: "הצהרת נגישות | Accessibility Statement — BEITON & Co",
  robots: "noindex, follow",
};

const he = {
  title: "הצהרת נגישות",
  subtitle: "אתר notary.beiton.co",
  lastUpdated: "עדכון אחרון: מרץ 2026",
  sections: [
    {
      heading: "1. מחויבות לנגישות",
      body: 'משרד עורכי דין BEITON & Co מחויב להבטחת נגישות אתר האינטרנט שלו לאנשים עם מוגבלות, בהתאם לחוק שוויון זכויות לאנשים עם מוגבלות, התשנ"ח-1998, ולתקנות שוויון זכויות לאנשים עם מוגבלות (התאמות נגישות לשירות), התשע"ג-2013.',
    },
    {
      heading: "2. תקן נגישות",
      body: 'האתר עומד בדרישות תקן ישראלי ת"י 5568 לנגישות תכנים באינטרנט, ברמת AA, המבוסס על הנחיות WCAG 2.1 של ארגון W3C.',
    },
    {
      heading: "3. התאמות נגישות שבוצעו",
      body: "באתר בוצעו, בין היתר, ההתאמות הבאות: מבנה כותרות היררכי ותקין (H1-H3), ניווט מלא באמצעות מקלדת, תמיכה בקוראי מסך, ניגודיות צבעים מספקת בין טקסט לרקע, תמיכה מלאה בכיוון RTL (עברית וערבית) ו-LTR (אנגלית, רוסית, צרפתית, ספרדית), טפסים עם תוויות נגישות, וטקסט חלופי לאייקונים ואלמנטים גרפיים.",
    },
    {
      heading: "4. דפדפנים נתמכים",
      body: "בדיקת הנגישות בוצעה בדפדפנים: Google Chrome, Mozilla Firefox, Apple Safari, Microsoft Edge (גרסאות אחרונות).",
    },
    {
      heading: "5. רכיבים שטרם הונגשו",
      body: "ייתכן כי חלק מתכני הצ'אט המופקים באמצעות בינה מלאכותית אינם מונגשים באופן מלא. המשרד פועל לשפר רכיבים אלה באופן שוטף. בכל מקרה של קושי, ניתן ליצור קשר ולקבל את השירות באופן חלופי.",
    },
    {
      heading: "6. נגישות פיזית",
      body: "משרדי BEITON & Co נגישים לאנשים עם מוגבלות. המשרד מציע גם שירות נוטריון עד הבית ללקוחות שאינם יכולים להגיע פיזית למשרד.",
    },
    {
      heading: "7. רכז/ת נגישות ויצירת קשר",
      body: "נתקלתם בבעיית נגישות באתר? נשמח לטפל בכך.\nדוא\"ל: office@beiton.co\nטלפון: 03-3817776\nפניות בנושא נגישות יטופלו בתוך 14 ימי עסקים.",
    },
    {
      heading: "8. הגשת תלונה",
      body: "אם פנייתך לא טופלה לשביעות רצונך, ניתן לפנות לנציבות שוויון זכויות לאנשים עם מוגבלות במשרד המשפטים:\nטלפון: 073-392-5999\nאתר: https://www.gov.il/he/departments/topics/persons_with_disabilities",
    },
  ],
};

const en = {
  title: "Accessibility Statement",
  subtitle: "notary.beiton.co",
  lastUpdated: "Last updated: March 2026",
  sections: [
    {
      heading: "1. Commitment to Accessibility",
      body: "BEITON & Co, Law Firm is committed to ensuring the accessibility of its website to persons with disabilities, in accordance with the Equal Rights for Persons with Disabilities Law, 1998, and the Equal Rights for Persons with Disabilities Regulations (Accessibility Adjustments to Service), 2013.",
    },
    {
      heading: "2. Accessibility Standard",
      body: "The Website complies with Israeli Standard SI 5568 for web content accessibility, at AA level, based on the WCAG 2.1 guidelines of the W3C.",
    },
    {
      heading: "3. Accessibility Adjustments Made",
      body: "The following adjustments have been implemented on the Website: hierarchical and valid heading structure (H1-H3), full keyboard navigation, screen reader support, sufficient color contrast between text and background, full support for RTL direction (Hebrew and Arabic) and LTR direction (English, Russian, French, Spanish), accessible form labels, and alternative text for icons and graphic elements.",
    },
    {
      heading: "4. Supported Browsers",
      body: "Accessibility testing was performed on the following browsers: Google Chrome, Mozilla Firefox, Apple Safari, and Microsoft Edge (latest versions).",
    },
    {
      heading: "5. Components Not Yet Accessible",
      body: "Some chat content generated by artificial intelligence may not be fully accessible. The Firm is working to improve these components on an ongoing basis. In any case of difficulty, please contact us to receive the service through an alternative method.",
    },
    {
      heading: "6. Physical Accessibility",
      body: "The offices of BEITON & Co are accessible to persons with disabilities. The Firm also offers notary home visit services for clients who are unable to visit the office in person.",
    },
    {
      heading: "7. Accessibility Coordinator and Contact",
      body: "Encountered an accessibility issue on the Website? We would be happy to address it.\nEmail: office@beiton.co\nPhone: 03-3817776\nAccessibility inquiries will be addressed within 14 business days.",
    },
    {
      heading: "8. Filing a Complaint",
      body: "If your inquiry was not resolved to your satisfaction, you may contact the Commission for Equal Rights of Persons with Disabilities at the Ministry of Justice:\nPhone: 073-392-5999\nWebsite: https://www.gov.il/he/departments/topics/persons_with_disabilities",
    },
  ],
};

export default async function AccessibilityPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  const content = locale === "he" ? he : en;

  return <LegalPage locale={locale as Locale} content={content} />;
}
